server:
  port: 8080

spring:
  application:
    name: small-business-customer-care
  ai:
    mcp:
      server:
        name: small-business-customer-care
        version: 0.0.1
  main:
    banner-mode: off
    logging:
      pattern:
        console: ""