spring:
  application:
    name: small-business-customer-care
  main:
    banner-mode: off
    web-application-type: none
    keep-alive: true
    
logging:
  pattern:
    console: ""
  level:
    root: off
    com.ravikalla: off